CREATE TABLE IF NOT EXISTS `accounting_fixed_asset_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `asset_item_no` varchar(40) NOT NULL,
  `name` varchar(150) NOT NULL,
  `brand` varchar(120) DEFAULT NULL,
  `category` varchar(120) NOT NULL,
  `sub_category` varchar(120) DEFAULT NULL,
  `depreciation_method` enum('straight_line') NOT NULL DEFAULT 'straight_line',
  `useful_life_months` int NOT NULL DEFAULT '36',
  `salvage_value` decimal(15,2) NOT NULL DEFAULT '0.00',
  `notes` varchar(1000) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_accounting_fixed_asset_items_no` (`client_id`,`asset_item_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `accounting_fixed_asset_units` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `asset_item_id` int NOT NULL,
  `unit_number` int NOT NULL,
  `branch_id` int NOT NULL,
  `model` varchar(150) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `serial_no` varchar(120) DEFAULT NULL,
  `tag_no` varchar(120) NOT NULL,
  `purchase_price` decimal(15,2) NOT NULL DEFAULT '0.00',
  `purchase_condition` enum('new','used_working','used_fair','refurbished') NOT NULL DEFAULT 'new',
  `capitalization_date` date NOT NULL,
  `purchase_order_no` varchar(100) DEFAULT NULL,
  `invoice_no` varchar(100) DEFAULT NULL,
  `supplier_name` varchar(150) DEFAULT NULL,
  `capitalization_mode` enum('cash','bank','credit_purchase') NOT NULL DEFAULT 'credit_purchase',
  `treasury_account_id` int DEFAULT NULL,
  `physical_location` varchar(180) DEFAULT NULL,
  `issued_to` varchar(150) DEFAULT NULL,
  `custodian_id` varchar(80) DEFAULT NULL,
  `issued_date` date DEFAULT NULL,
  `expected_return` date DEFAULT NULL,
  `condition` enum('working','service_required','damaged') NOT NULL DEFAULT 'working',
  `operational_status` enum('assigned','in_store','under_repair','stolen','lost','disposed') NOT NULL DEFAULT 'in_store',
  `warranty_expiry` date DEFAULT NULL,
  `last_service_date` date DEFAULT NULL,
  `next_service_due` date DEFAULT NULL,
  `insurance_expiry` date DEFAULT NULL,
  `disposal_no` varchar(60) DEFAULT NULL,
  `disposal_method` enum('auctioned','sold','donated','scrapped','transferred','written_off') DEFAULT NULL,
  `disposal_date` date DEFAULT NULL,
  `disposal_amount` decimal(15,2) NOT NULL DEFAULT '0.00',
  `disposal_recipient` varchar(180) DEFAULT NULL,
  `disposal_note` varchar(1000) DEFAULT NULL,
  `disposal_approved_by` varchar(150) DEFAULT NULL,
  `disposal_reason_code` varchar(80) DEFAULT NULL,
  `comments` varchar(1000) DEFAULT NULL,
  `capitalization_journal_entry_id` int DEFAULT NULL,
  `disposal_journal_entry_id` int DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_accounting_fixed_asset_units_item_unit` (`client_id`,`asset_item_id`,`unit_number`),
  UNIQUE KEY `IDX_accounting_fixed_asset_units_tag` (`client_id`,`tag_no`),
  KEY `IDX_accounting_fixed_asset_units_branch` (`branch_id`),
  KEY `IDX_accounting_fixed_asset_units_status` (`client_id`,`operational_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `accounting_fixed_asset_movements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `asset_unit_id` int NOT NULL,
  `movement_type` enum('acquisition','issue','return','transfer','disposal') NOT NULL,
  `movement_date` date NOT NULL,
  `from_branch_id` int DEFAULT NULL,
  `to_branch_id` int DEFAULT NULL,
  `from_location` varchar(180) DEFAULT NULL,
  `to_location` varchar(180) DEFAULT NULL,
  `from_custodian` varchar(150) DEFAULT NULL,
  `to_custodian` varchar(150) DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `authorized_by` varchar(150) DEFAULT NULL,
  `received_by` varchar(150) DEFAULT NULL,
  `vehicle_no` varchar(80) DEFAULT NULL,
  `gate_pass_no` varchar(80) DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `journal_entry_id` int DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_accounting_fixed_asset_movements_unit_date` (`client_id`,`asset_unit_id`,`movement_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
