CREATE TABLE IF NOT EXISTS `accounting_payroll_runs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `run_no` varchar(60) NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `pay_date` date NOT NULL,
  `status` enum('draft','approved','paid','void') NOT NULL DEFAULT 'draft',
  `employee_count` int NOT NULL DEFAULT 0,
  `total_base_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_gross_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_deduction_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_net_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `notes` text NULL,
  `payment_method` varchar(50) NULL,
  `payment_reference_no` varchar(100) NULL,
  `treasury_account_id` int NULL,
  `accrual_journal_entry_id` int NULL,
  `payment_journal_entry_id` int NULL,
  `reversal_journal_entry_id` int NULL,
  `approved_at` datetime NULL,
  `approved_by` int NULL,
  `paid_at` datetime NULL,
  `paid_by` int NULL,
  `voided_at` datetime NULL,
  `voided_by` int NULL,
  `created_by` int NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounting_payroll_runs_scope` (`client_id`,`branch_id`,`period_start`,`period_end`),
  KEY `idx_accounting_payroll_runs_branch` (`client_id`,`branch_id`),
  CONSTRAINT `fk_accounting_payroll_runs_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_payroll_runs_treasury_account` FOREIGN KEY (`treasury_account_id`) REFERENCES `accounting_coa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_payroll_runs_accrual_journal` FOREIGN KEY (`accrual_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_payroll_runs_payment_journal` FOREIGN KEY (`payment_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_payroll_runs_reversal_journal` FOREIGN KEY (`reversal_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `accounting_payroll_run_lines` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payroll_run_id` int NOT NULL,
  `user_id` int NULL,
  `employee_id_snapshot` varchar(50) NULL,
  `staff_name_snapshot` varchar(180) NOT NULL,
  `employment_type_snapshot` varchar(50) NULL,
  `salary_type` varchar(50) NULL,
  `salary_rate` decimal(15,2) NOT NULL DEFAULT 0.00,
  `present_days` int NOT NULL DEFAULT 0,
  `late_days` int NOT NULL DEFAULT 0,
  `leave_days` int NOT NULL DEFAULT 0,
  `absent_days` int NOT NULL DEFAULT 0,
  `working_minutes` int NOT NULL DEFAULT 0,
  `payable_units` decimal(10,2) NOT NULL DEFAULT 0.00,
  `base_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `gross_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `deduction_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `net_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_accounting_payroll_lines_run` (`payroll_run_id`),
  KEY `idx_accounting_payroll_lines_user` (`user_id`),
  CONSTRAINT `fk_accounting_payroll_lines_run` FOREIGN KEY (`payroll_run_id`) REFERENCES `accounting_payroll_runs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_payroll_lines_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
