CREATE TABLE IF NOT EXISTS pos_devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id VARCHAR(20) NOT NULL,
  branch_id INT NOT NULL,
  device_uid VARCHAR(100) NOT NULL,
  device_code VARCHAR(50) NULL,
  device_name VARCHAR(100) NULL,
  device_type ENUM('pos_terminal','kds','order_taker','backoffice','other') NOT NULL DEFAULT 'pos_terminal',
  device_os VARCHAR(50) NULL,
  app_version VARCHAR(50) NULL,
  status ENUM('active','inactive','blocked') NOT NULL DEFAULT 'active',
  last_seen_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pos_devices_client_uid (client_id, device_uid),
  KEY idx_pos_devices_client_branch (client_id, branch_id),
  KEY idx_pos_devices_branch (branch_id),
  CONSTRAINT fk_pos_devices_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_pos_devices_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pos_sync_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id VARCHAR(20) NOT NULL,
  branch_id INT NOT NULL,
  device_id INT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id VARCHAR(64) NULL,
  event_type ENUM('upsert','delete','sync') NOT NULL DEFAULT 'upsert',
  payload_hash VARCHAR(64) NOT NULL,
  status ENUM('pending','processed','failed') NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  last_attempt_at DATETIME NULL,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pos_sync_events_client_branch (client_id, branch_id),
  KEY idx_pos_sync_events_device_status (device_id, status),
  KEY idx_pos_sync_events_entity (entity_type, entity_id),
  CONSTRAINT fk_pos_sync_events_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_pos_sync_events_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_pos_sync_events_device FOREIGN KEY (device_id) REFERENCES pos_devices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
