ALTER TABLE `client_settings`
  MODIFY COLUMN `company_logo_url` text NULL,
  ADD COLUMN `short_logo_url` text NULL AFTER `company_logo_url`,
  ADD COLUMN `login_background_url` text NULL AFTER `short_logo_url`,
  ADD COLUMN `receipt_business_name` varchar(150) NULL AFTER `login_background_url`,
  ADD COLUMN `receipt_footer_message_1` varchar(255) NULL AFTER `receipt_business_name`,
  ADD COLUMN `receipt_footer_message_2` varchar(255) NULL AFTER `receipt_footer_message_1`,
  ADD COLUMN `show_receipt_full_logo` tinyint(1) NOT NULL DEFAULT 1 AFTER `receipt_footer_message_2`,
  ADD COLUMN `show_receipt_short_logo` tinyint(1) NOT NULL DEFAULT 0 AFTER `show_receipt_full_logo`,
  ADD COLUMN `show_receipt_business_name` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_short_logo`,
  ADD COLUMN `show_receipt_branch_name` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_business_name`,
  ADD COLUMN `show_receipt_branch_address` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_branch_name`,
  ADD COLUMN `show_receipt_contact_number` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_branch_address`,
  ADD COLUMN `show_receipt_footer_message_1` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_contact_number`,
  ADD COLUMN `show_receipt_footer_message_2` tinyint(1) NOT NULL DEFAULT 0 AFTER `show_receipt_footer_message_1`,
  ADD COLUMN `show_login_full_logo` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_receipt_footer_message_2`,
  ADD COLUMN `show_login_business_name` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_login_full_logo`,
  ADD COLUMN `show_login_branch_name` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_login_business_name`,
  ADD COLUMN `show_header_short_logo` tinyint(1) NOT NULL DEFAULT 1 AFTER `show_login_branch_name`;
