ALTER TABLE `users`
  ADD COLUMN `father_husband_name` varchar(150) NULL AFTER `address`,
  ADD COLUMN `gender` varchar(20) NULL AFTER `father_husband_name`,
  ADD COLUMN `religion` varchar(50) NULL AFTER `gender`,
  ADD COLUMN `sect` varchar(50) NULL AFTER `religion`,
  ADD COLUMN `date_of_birth` date NULL AFTER `sect`,
  ADD COLUMN `locality` varchar(120) NULL AFTER `date_of_birth`,
  ADD COLUMN `city` varchar(100) NULL AFTER `locality`,
  ADD COLUMN `country` varchar(100) NULL AFTER `city`,
  ADD COLUMN `joining_date` date NULL AFTER `country`,
  ADD COLUMN `employment_type` varchar(50) NULL AFTER `joining_date`,
  ADD COLUMN `leaving_date` date NULL AFTER `employment_type`,
  ADD COLUMN `current_salary` decimal(12,2) NULL AFTER `leaving_date`,
  ADD COLUMN `salary_type` varchar(50) NULL AFTER `current_salary`,
  ADD COLUMN `salary_revision_date` date NULL AFTER `salary_type`,
  ADD COLUMN `hr_remarks` text NULL AFTER `salary_revision_date`,
  ADD COLUMN `vehicle_type` varchar(50) NULL AFTER `hr_remarks`,
  ADD COLUMN `vehicle_reg_no` varchar(50) NULL AFTER `vehicle_type`,
  ADD COLUMN `vehicle_make_model` varchar(150) NULL AFTER `vehicle_reg_no`,
  ADD COLUMN `vehicle_color` varchar(50) NULL AFTER `vehicle_make_model`,
  ADD COLUMN `bank_name` varchar(120) NULL AFTER `vehicle_color`,
  ADD COLUMN `account_title` varchar(150) NULL AFTER `bank_name`,
  ADD COLUMN `account_number` varchar(100) NULL AFTER `account_title`,
  ADD COLUMN `force_password_change` tinyint(1) NOT NULL DEFAULT 0 AFTER `account_number`,
  ADD COLUMN `attachments` json NULL AFTER `force_password_change`;
