ALTER TABLE `branches`
  ADD COLUMN `inventory_store_type` enum('branch','central') NOT NULL DEFAULT 'branch' AFTER `inherit_client_theme`;

CREATE TABLE `inventory_transfers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `transfer_no` varchar(50) NOT NULL,
  `source_branch_id` int NOT NULL,
  `destination_branch_id` int NOT NULL,
  `source_store_label` varchar(100) DEFAULT NULL,
  `destination_store_label` varchar(100) DEFAULT NULL,
  `reason_code` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `require_approval` tinyint(1) NOT NULL DEFAULT 1,
  `status` enum('requested','approved','rejected','in_transit','received','received_with_variance') NOT NULL DEFAULT 'requested',
  `requested_by` varchar(100) DEFAULT NULL,
  `requested_by_name` varchar(150) DEFAULT NULL,
  `requested_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_by_name` varchar(150) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approval_notes` text DEFAULT NULL,
  `rejected_by` varchar(100) DEFAULT NULL,
  `rejected_by_name` varchar(150) DEFAULT NULL,
  `rejected_at` datetime DEFAULT NULL,
  `rejection_notes` text DEFAULT NULL,
  `dispatched_by` varchar(100) DEFAULT NULL,
  `dispatched_by_name` varchar(150) DEFAULT NULL,
  `dispatched_at` datetime DEFAULT NULL,
  `dispatch_notes` text DEFAULT NULL,
  `received_by` varchar(100) DEFAULT NULL,
  `received_by_name` varchar(150) DEFAULT NULL,
  `received_at` datetime DEFAULT NULL,
  `receipt_notes` text DEFAULT NULL,
  `variance_notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_inventory_transfers_client_transfer_no` (`client_id`, `transfer_no`),
  KEY `IDX_inventory_transfers_client_status` (`client_id`, `status`),
  KEY `IDX_inventory_transfers_client_source_branch` (`client_id`, `source_branch_id`),
  KEY `IDX_inventory_transfers_client_destination_branch` (`client_id`, `destination_branch_id`),
  CONSTRAINT `FK_inventory_transfers_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_inventory_transfers_source_branch` FOREIGN KEY (`source_branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_inventory_transfers_destination_branch` FOREIGN KEY (`destination_branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE `inventory_transfer_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `transfer_id` int NOT NULL,
  `item_id` int NOT NULL,
  `requested_quantity` decimal(15,4) NOT NULL,
  `dispatched_quantity` decimal(15,4) NOT NULL DEFAULT 0,
  `received_quantity` decimal(15,4) NOT NULL DEFAULT 0,
  `short_quantity` decimal(15,4) NOT NULL DEFAULT 0,
  `damaged_quantity` decimal(15,4) NOT NULL DEFAULT 0,
  `unit_cost` decimal(15,4) NOT NULL DEFAULT 0,
  `variance_reason` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_inventory_transfer_items_transfer` (`transfer_id`),
  KEY `IDX_inventory_transfer_items_client_item` (`client_id`, `item_id`),
  CONSTRAINT `FK_inventory_transfer_items_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_inventory_transfer_items_transfer` FOREIGN KEY (`transfer_id`) REFERENCES `inventory_transfers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_inventory_transfer_items_item` FOREIGN KEY (`item_id`) REFERENCES `inventory_items` (`id`)
);

CREATE TABLE `inventory_transfer_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `transfer_id` int NOT NULL,
  `action` enum('requested','approved','rejected','dispatched','received') NOT NULL,
  `status_after` varchar(50) NOT NULL,
  `actor_id` varchar(100) DEFAULT NULL,
  `actor_name` varchar(150) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `metadata_json` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_inventory_transfer_events_client_transfer` (`client_id`, `transfer_id`),
  KEY `IDX_inventory_transfer_events_transfer_created_at` (`transfer_id`, `created_at`),
  CONSTRAINT `FK_inventory_transfer_events_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_inventory_transfer_events_transfer` FOREIGN KEY (`transfer_id`) REFERENCES `inventory_transfers` (`id`) ON DELETE CASCADE
);
