CREATE TABLE IF NOT EXISTS `accounting_loans` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `loan_code` varchar(40) NOT NULL,
  `source_name` varchar(180) NOT NULL,
  `principal_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `annual_interest_rate` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `interest_method` enum('flat','reducing') NOT NULL,
  `start_date` date NOT NULL,
  `duration_months` int NOT NULL,
  `repayment_frequency` enum('monthly','quarterly') NOT NULL DEFAULT 'monthly',
  `installment_count` int NOT NULL,
  `installment_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `maturity_date` date DEFAULT NULL,
  `next_due_date` date DEFAULT NULL,
  `outstanding_principal_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `status` enum('active','completed','defaulted','closed') NOT NULL DEFAULT 'active',
  `disbursement_reference_no` varchar(100) DEFAULT NULL,
  `disbursement_account_id` int DEFAULT NULL,
  `liability_account_id` int DEFAULT NULL,
  `interest_expense_account_id` int DEFAULT NULL,
  `disbursement_journal_entry_id` int DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounting_loans_code` (`client_id`,`loan_code`),
  KEY `idx_accounting_loans_branch_status` (`client_id`,`branch_id`,`status`),
  CONSTRAINT `fk_accounting_loans_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loans_disbursement_account` FOREIGN KEY (`disbursement_account_id`) REFERENCES `accounting_coa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loans_liability_account` FOREIGN KEY (`liability_account_id`) REFERENCES `accounting_coa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loans_interest_expense_account` FOREIGN KEY (`interest_expense_account_id`) REFERENCES `accounting_coa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loans_disbursement_journal` FOREIGN KEY (`disbursement_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `accounting_loan_repayments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `loan_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `installment_no` int NOT NULL,
  `due_date` date NOT NULL,
  `principal_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `interest_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_due_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `principal_paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `interest_paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `paid_date` date DEFAULT NULL,
  `balance_after_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `status` enum('due','paid','overdue') NOT NULL DEFAULT 'due',
  `payment_method` varchar(50) DEFAULT NULL,
  `treasury_account_id` int DEFAULT NULL,
  `journal_entry_id` int DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounting_loan_repayments_installment` (`client_id`,`loan_id`,`installment_no`),
  KEY `idx_accounting_loan_repayments_branch_due` (`client_id`,`branch_id`,`due_date`),
  CONSTRAINT `fk_accounting_loan_repayments_loan` FOREIGN KEY (`loan_id`) REFERENCES `accounting_loans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loan_repayments_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loan_repayments_treasury_account` FOREIGN KEY (`treasury_account_id`) REFERENCES `accounting_coa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_loan_repayments_journal` FOREIGN KEY (`journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
