CREATE TABLE IF NOT EXISTS `authorized_tills` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `shift_id` int NOT NULL,
  `sale_counter_id` int NOT NULL,
  `assigned_float` decimal(12,2) NOT NULL DEFAULT '0.00',
  `blind_count` decimal(12,2) DEFAULT NULL,
  `expected_cash` decimal(12,2) DEFAULT NULL,
  `variance` decimal(12,2) DEFAULT NULL,
  `terminal_status` enum('open','active','blind_submitted','closed') NOT NULL DEFAULT 'open',
  `blind_submitted_at` datetime DEFAULT NULL,
  `reconciled_at` datetime DEFAULT NULL,
  `reconciled_by_user_id` int DEFAULT NULL,
  `reconciliation_notes` text DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_authorized_tills_client_branch_shift` (`client_id`,`branch_id`,`shift_id`),
  UNIQUE KEY `IDX_authorized_tills_unique` (`client_id`,`branch_id`,`shift_id`,`sale_counter_id`),
  CONSTRAINT `FK_auth_till_shift` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
