CREATE TABLE IF NOT EXISTS `branch_locations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `location_name` varchar(120) NOT NULL,
  `location_code` varchar(40) DEFAULT NULL,
  `location_type` varchar(40) NOT NULL DEFAULT 'store',
  `description` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_branch_locations_name` (`client_id`,`branch_id`,`location_name`),
  KEY `idx_branch_locations_branch` (`client_id`,`branch_id`),
  CONSTRAINT `fk_branch_locations_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_branch_locations_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_code`) ON DELETE CASCADE
);

ALTER TABLE `branches`
  ADD COLUMN IF NOT EXISTS `inventory_control_settings` json DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `inventory_count_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `location_id` int DEFAULT NULL,
  `session_code` varchar(40) NOT NULL,
  `title` varchar(180) NOT NULL,
  `count_type` enum('random_cycle','eod_blind_close','monthly_full') NOT NULL,
  `status` enum('scheduled','in_progress','submitted','under_review','reconciled','adjustment_pending','escalated','closed','cancelled') NOT NULL DEFAULT 'scheduled',
  `business_date` date DEFAULT NULL,
  `period_key` varchar(7) DEFAULT NULL,
  `selection_summary` json DEFAULT NULL,
  `thresholds` json DEFAULT NULL,
  `generated_by_user_id` varchar(50) DEFAULT NULL,
  `generated_by_name` varchar(150) DEFAULT NULL,
  `counted_by_user_id` varchar(50) DEFAULT NULL,
  `counted_by_name` varchar(150) DEFAULT NULL,
  `reviewed_by_user_id` varchar(50) DEFAULT NULL,
  `reviewed_by_name` varchar(150) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL,
  `line_count` int NOT NULL DEFAULT 0,
  `counted_line_count` int NOT NULL DEFAULT 0,
  `matched_line_count` int NOT NULL DEFAULT 0,
  `variance_line_count` int NOT NULL DEFAULT 0,
  `critical_line_count` int NOT NULL DEFAULT 0,
  `variance_quantity_total` decimal(15,4) NOT NULL DEFAULT 0,
  `variance_value_total` decimal(15,4) NOT NULL DEFAULT 0,
  `accuracy_score` decimal(7,2) NOT NULL DEFAULT 0,
  `escalation_required` tinyint(1) NOT NULL DEFAULT 0,
  `escalation_reason` varchar(255) DEFAULT NULL,
  `notes` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_count_sessions_code` (`session_code`),
  KEY `idx_inventory_count_sessions_branch` (`client_id`,`branch_id`,`status`),
  KEY `idx_inventory_count_sessions_type_date` (`client_id`,`branch_id`,`count_type`,`business_date`),
  CONSTRAINT `fk_inventory_count_sessions_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_count_sessions_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_code`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_count_sessions_location` FOREIGN KEY (`location_id`) REFERENCES `branch_locations` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `inventory_count_session_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `session_id` int NOT NULL,
  `location_id` int DEFAULT NULL,
  `item_id` int NOT NULL,
  `blind_sequence` int NOT NULL DEFAULT 0,
  `expected_quantity_snapshot` decimal(15,4) NOT NULL DEFAULT 0,
  `counted_quantity` decimal(15,4) DEFAULT NULL,
  `variance_quantity` decimal(15,4) NOT NULL DEFAULT 0,
  `variance_percent` decimal(9,2) NOT NULL DEFAULT 0,
  `estimated_unit_cost` decimal(15,4) NOT NULL DEFAULT 0,
  `variance_value` decimal(15,4) NOT NULL DEFAULT 0,
  `discrepancy_level` enum('none','low','medium','high','critical') NOT NULL DEFAULT 'none',
  `review_status` varchar(30) NOT NULL DEFAULT 'pending',
  `review_action` enum('accept','recount','adjust_stock','escalate') DEFAULT NULL,
  `reason_code` varchar(60) DEFAULT NULL,
  `review_notes` varchar(500) DEFAULT NULL,
  `adjustment_reference_id` varchar(100) DEFAULT NULL,
  `counted_at` datetime DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_count_session_item` (`session_id`,`item_id`),
  KEY `idx_inventory_count_items_level` (`client_id`,`branch_id`,`discrepancy_level`),
  CONSTRAINT `fk_inventory_count_items_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_count_items_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_code`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_count_items_item` FOREIGN KEY (`item_id`) REFERENCES `inventory_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_count_items_location` FOREIGN KEY (`location_id`) REFERENCES `branch_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_inventory_count_items_session` FOREIGN KEY (`session_id`) REFERENCES `inventory_count_sessions` (`id`) ON DELETE CASCADE
);
