ALTER TABLE `users`
  ADD COLUMN `father_husband_name` varchar(150) NULL,
  ADD COLUMN `gender` varchar(20) NULL,
  ADD COLUMN `religion` varchar(50) NULL,
  ADD COLUMN `sect` varchar(50) NULL,
  ADD COLUMN `date_of_birth` date NULL,
  ADD COLUMN `locality` varchar(120) NULL,
  ADD COLUMN `city` varchar(100) NULL,
  ADD COLUMN `country` varchar(100) NULL,
  ADD COLUMN `joining_date` date NULL,
  ADD COLUMN `employment_type` varchar(50) NULL,
  ADD COLUMN `leaving_date` date NULL,
  ADD COLUMN `current_salary` decimal(12,2) NULL,
  ADD COLUMN `salary_type` varchar(50) NULL,
  ADD COLUMN `salary_revision_date` date NULL,
  ADD COLUMN `hr_remarks` text NULL,
  ADD COLUMN `vehicle_type` varchar(50) NULL,
  ADD COLUMN `vehicle_reg_no` varchar(50) NULL,
  ADD COLUMN `vehicle_make_model` varchar(150) NULL,
  ADD COLUMN `vehicle_color` varchar(50) NULL,
  ADD COLUMN `bank_name` varchar(120) NULL,
  ADD COLUMN `account_title` varchar(150) NULL,
  ADD COLUMN `account_number` varchar(100) NULL,
  ADD COLUMN `force_password_change` tinyint(1) NOT NULL DEFAULT 0,
  ADD COLUMN `attachments` json NULL;
