CREATE TABLE IF NOT EXISTS `catering_inquiries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `customer_id` int DEFAULT NULL,
  `inquiry_no` varchar(50) NOT NULL,
  `event_title` varchar(150) NOT NULL,
  `service_type` enum('on_premise','offsite','delivery','pickup') NOT NULL DEFAULT 'offsite',
  `event_date` date NOT NULL,
  `start_time` varchar(5) DEFAULT NULL,
  `end_time` varchar(5) DEFAULT NULL,
  `guest_count` int NOT NULL DEFAULT 1,
  `venue_name` varchar(150) DEFAULT NULL,
  `venue_address` text,
  `contact_name` varchar(150) DEFAULT NULL,
  `contact_phone` varchar(30) DEFAULT NULL,
  `contact_email` varchar(150) DEFAULT NULL,
  `budget_amount` decimal(12,2) DEFAULT NULL,
  `status` enum('open','quoted','won','lost','cancelled') NOT NULL DEFAULT 'open',
  `notes` text,
  `captured_by` varchar(100) DEFAULT NULL,
  `captured_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_catering_inquiries_client_inquiry_no` (`client_id`,`inquiry_no`),
  KEY `IDX_catering_inquiries_branch` (`client_id`,`branch_id`),
  KEY `IDX_catering_inquiries_status` (`client_id`,`status`),
  KEY `IDX_catering_inquiries_event_date` (`client_id`,`event_date`),
  CONSTRAINT `FK_catering_inquiries_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_inquiries_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_inquiries_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_quotations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `inquiry_id` int NOT NULL,
  `quote_no` varchar(50) NOT NULL,
  `revision_no` int NOT NULL DEFAULT 1,
  `status` enum('draft','sent','approved','rejected','expired','converted') NOT NULL DEFAULT 'draft',
  `valid_until` date DEFAULT NULL,
  `subtotal_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estimated_cost_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `service_charge_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `margin_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `terms_and_conditions` text,
  `notes` text,
  `prepared_by` varchar(100) DEFAULT NULL,
  `prepared_by_name` varchar(150) DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_by_name` varchar(150) DEFAULT NULL,
  `rejection_reason` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_catering_quotations_client_quote_no` (`client_id`,`quote_no`),
  KEY `IDX_catering_quotations_branch` (`client_id`,`branch_id`),
  KEY `IDX_catering_quotations_status` (`client_id`,`status`),
  KEY `IDX_catering_quotations_inquiry` (`client_id`,`inquiry_id`),
  CONSTRAINT `FK_catering_quotations_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_quotations_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_quotations_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `catering_inquiries` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_quotation_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `quotation_id` int NOT NULL,
  `item_type` enum('product','inventory','service','fee','discount','other') NOT NULL DEFAULT 'product',
  `product_id` int DEFAULT NULL,
  `inventory_item_id` int DEFAULT NULL,
  `recipe_id` int DEFAULT NULL,
  `line_description` varchar(255) NOT NULL,
  `quantity` decimal(12,4) NOT NULL DEFAULT 0.0000,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estimated_unit_cost` decimal(12,4) NOT NULL DEFAULT 0.0000,
  `estimated_total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `supply_strategy` enum('none','produce','procure','both') NOT NULL DEFAULT 'none',
  `service_notes` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_catering_quotation_items_quotation` (`client_id`,`quotation_id`),
  CONSTRAINT `FK_catering_quotation_items_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_quotation_items_quotation` FOREIGN KEY (`quotation_id`) REFERENCES `catering_quotations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_catering_quotation_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `FK_catering_quotation_items_inventory_item` FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items` (`id`),
  CONSTRAINT `FK_catering_quotation_items_recipe` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `inquiry_id` int NOT NULL,
  `quotation_id` int NOT NULL,
  `customer_id` int DEFAULT NULL,
  `execution_branch_id` int NOT NULL,
  `production_branch_id` int DEFAULT NULL,
  `event_no` varchar(50) NOT NULL,
  `event_title` varchar(150) NOT NULL,
  `service_type` enum('on_premise','offsite','delivery','pickup') NOT NULL DEFAULT 'offsite',
  `event_date` date NOT NULL,
  `start_time` varchar(5) DEFAULT NULL,
  `end_time` varchar(5) DEFAULT NULL,
  `guest_count` int NOT NULL DEFAULT 1,
  `venue_name` varchar(150) DEFAULT NULL,
  `venue_address` text,
  `coordinator_name` varchar(150) DEFAULT NULL,
  `coordinator_phone` varchar(30) DEFAULT NULL,
  `status` enum('planned','confirmed','in_production','ready','completed','cancelled') NOT NULL DEFAULT 'planned',
  `billing_status` enum('unbilled','billed','partially_paid','paid') NOT NULL DEFAULT 'unbilled',
  `quoted_total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estimated_cost_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `actual_total_amount` decimal(12,2) DEFAULT NULL,
  `total_paid_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `billing_journal_entry_id` int DEFAULT NULL,
  `billing_issued_at` datetime DEFAULT NULL,
  `notes` text,
  `confirmed_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_catering_events_client_event_no` (`client_id`,`event_no`),
  KEY `IDX_catering_events_event_date` (`client_id`,`event_date`),
  KEY `IDX_catering_events_status` (`client_id`,`status`),
  KEY `IDX_catering_events_execution_branch` (`client_id`,`execution_branch_id`),
  CONSTRAINT `FK_catering_events_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_events_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `catering_inquiries` (`id`),
  CONSTRAINT `FK_catering_events_quotation` FOREIGN KEY (`quotation_id`) REFERENCES `catering_quotations` (`id`),
  CONSTRAINT `FK_catering_events_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `FK_catering_events_execution_branch` FOREIGN KEY (`execution_branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_events_production_branch` FOREIGN KEY (`production_branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_events_billing_entry` FOREIGN KEY (`billing_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_event_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `event_id` int NOT NULL,
  `product_id` int DEFAULT NULL,
  `inventory_item_id` int DEFAULT NULL,
  `recipe_id` int DEFAULT NULL,
  `item_type` enum('product','inventory','service','fee','discount','other') NOT NULL DEFAULT 'product',
  `line_description` varchar(255) NOT NULL,
  `quantity` decimal(12,4) NOT NULL DEFAULT 0.0000,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estimated_unit_cost` decimal(12,4) NOT NULL DEFAULT 0.0000,
  `estimated_total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `supply_strategy` enum('none','produce','procure','both') NOT NULL DEFAULT 'none',
  `production_notes` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_catering_event_items_event` (`client_id`,`event_id`),
  CONSTRAINT `FK_catering_event_items_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_event_items_event` FOREIGN KEY (`event_id`) REFERENCES `catering_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_catering_event_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `FK_catering_event_items_inventory_item` FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items` (`id`),
  CONSTRAINT `FK_catering_event_items_recipe` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_event_procurement_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `event_id` int NOT NULL,
  `procurement_request_id` int NOT NULL,
  `source_branch_id` int NOT NULL,
  `destination_branch_id` int NOT NULL,
  `event_item_ids_json` json DEFAULT NULL,
  `notes` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_catering_event_procurement_request` (`client_id`,`procurement_request_id`),
  KEY `IDX_catering_event_procurement_links_event` (`client_id`,`event_id`),
  CONSTRAINT `FK_catering_event_procurement_links_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_event_procurement_links_event` FOREIGN KEY (`event_id`) REFERENCES `catering_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_catering_event_procurement_links_request` FOREIGN KEY (`procurement_request_id`) REFERENCES `procurement_requests` (`id`),
  CONSTRAINT `FK_catering_event_procurement_links_source_branch` FOREIGN KEY (`source_branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_event_procurement_links_destination_branch` FOREIGN KEY (`destination_branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_event_production_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `event_id` int NOT NULL,
  `production_order_id` int NOT NULL,
  `event_item_id` int NOT NULL,
  `source_branch_id` int NOT NULL,
  `destination_branch_id` int NOT NULL,
  `notes` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_catering_event_production_order` (`client_id`,`production_order_id`),
  KEY `IDX_catering_event_production_links_event` (`client_id`,`event_id`),
  CONSTRAINT `FK_catering_event_production_links_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_event_production_links_event` FOREIGN KEY (`event_id`) REFERENCES `catering_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_catering_event_production_links_order` FOREIGN KEY (`production_order_id`) REFERENCES `production_orders` (`id`),
  CONSTRAINT `FK_catering_event_production_links_event_item` FOREIGN KEY (`event_item_id`) REFERENCES `catering_event_items` (`id`),
  CONSTRAINT `FK_catering_event_production_links_source_branch` FOREIGN KEY (`source_branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_event_production_links_destination_branch` FOREIGN KEY (`destination_branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `catering_event_settlements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `event_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `payment_date` date NOT NULL,
  `payment_mode` enum('cash','bank','card','online','cheque','other') NOT NULL DEFAULT 'cash',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `reference_no` varchar(100) DEFAULT NULL,
  `notes` text,
  `accounting_journal_entry_id` int DEFAULT NULL,
  `recorded_by` varchar(100) DEFAULT NULL,
  `recorded_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_catering_event_settlements_event` (`client_id`,`event_id`),
  KEY `IDX_catering_event_settlements_entry` (`client_id`,`accounting_journal_entry_id`),
  CONSTRAINT `FK_catering_event_settlements_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_catering_event_settlements_event` FOREIGN KEY (`event_id`) REFERENCES `catering_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_catering_event_settlements_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_catering_event_settlements_entry` FOREIGN KEY (`accounting_journal_entry_id`) REFERENCES `accounting_journal_entries` (`id`)
);
