ALTER TABLE uoms
  ADD COLUMN IF NOT EXISTS uom_type VARCHAR(20) NOT NULL DEFAULT 'count';

ALTER TABLE recipes
  ADD COLUMN IF NOT EXISTS is_locked TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locked_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS locked_total_cost DECIMAL(15,4) NULL;
