CREATE TABLE IF NOT EXISTS `accounting_investors` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `investor_code` varchar(40) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `primary_branch_id` int DEFAULT NULL,
  `status` enum('active','inactive','suspended','closed') NOT NULL DEFAULT 'active',
  `notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_accounting_investors_code` (`client_id`, `investor_code`),
  KEY `IDX_accounting_investors_name` (`client_id`, `full_name`),
  CONSTRAINT `FK_accounting_investors_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_accounting_investors_primary_branch` FOREIGN KEY (`primary_branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `accounting_investor_agreements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `investor_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `agreement_code` varchar(40) NOT NULL,
  `agreement_name` varchar(150) NOT NULL,
  `agreement_type` enum('profit_share','fixed_return','hybrid') NOT NULL,
  `distribution_frequency` enum('monthly','quarterly') NOT NULL DEFAULT 'monthly',
  `capital_commitment_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `current_capital_balance` decimal(15,2) NOT NULL DEFAULT 0.00,
  `profit_share_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `fixed_return_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `management_charge_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `total_distributed_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `status` enum('draft','active','matured','closed') NOT NULL DEFAULT 'draft',
  `notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_accounting_investor_agreements_code` (`client_id`, `agreement_code`),
  KEY `IDX_accounting_investor_agreements_branch_status` (`client_id`, `branch_id`, `status`),
  KEY `IDX_accounting_investor_agreements_investor_branch` (`client_id`, `investor_id`, `branch_id`),
  CONSTRAINT `FK_accounting_investor_agreements_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_accounting_investor_agreements_investor` FOREIGN KEY (`investor_id`) REFERENCES `accounting_investors` (`id`),
  CONSTRAINT `FK_accounting_investor_agreements_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `accounting_profit_distribution_batches` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `branch_id` int NOT NULL,
  `batch_code` varchar(40) DEFAULT NULL,
  `distribution_frequency` enum('monthly','quarterly') NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `net_profit_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `positive_profit_basis_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_management_charge_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_distribution_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `status` enum('processed') NOT NULL DEFAULT 'processed',
  `processed_at` datetime DEFAULT NULL,
  `processed_by_user_id` int DEFAULT NULL,
  `processed_by_name` varchar(150) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_accounting_profit_distribution_batches_period` (`client_id`, `branch_id`, `distribution_frequency`, `period_start`, `period_end`),
  CONSTRAINT `FK_accounting_profit_distribution_batches_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_accounting_profit_distribution_batches_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `accounting_profit_distribution_lines` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `batch_id` int NOT NULL,
  `investor_id` int NOT NULL,
  `agreement_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `capital_basis_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `profit_share_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `fixed_return_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `management_charge_percent` decimal(7,4) NOT NULL DEFAULT 0.0000,
  `profit_share_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `fixed_return_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `gross_distribution_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `management_charge_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `net_distribution_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_accounting_profit_distribution_lines_batch` (`client_id`, `batch_id`),
  KEY `IDX_accounting_profit_distribution_lines_agreement` (`client_id`, `agreement_id`),
  CONSTRAINT `FK_accounting_profit_distribution_lines_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_accounting_profit_distribution_lines_batch` FOREIGN KEY (`batch_id`) REFERENCES `accounting_profit_distribution_batches` (`id`),
  CONSTRAINT `FK_accounting_profit_distribution_lines_investor` FOREIGN KEY (`investor_id`) REFERENCES `accounting_investors` (`id`),
  CONSTRAINT `FK_accounting_profit_distribution_lines_agreement` FOREIGN KEY (`agreement_id`) REFERENCES `accounting_investor_agreements` (`id`),
  CONSTRAINT `FK_accounting_profit_distribution_lines_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`)
);

CREATE TABLE IF NOT EXISTS `accounting_investor_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` varchar(20) NOT NULL,
  `investor_id` int NOT NULL,
  `agreement_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `distribution_batch_id` int DEFAULT NULL,
  `transaction_date` date NOT NULL,
  `transaction_type` enum('capital_injection','capital_withdrawal','capital_return','manual_increase','manual_decrease','profit_distribution','management_charge') NOT NULL,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `description` varchar(255) DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `period_start` date DEFAULT NULL,
  `period_end` date DEFAULT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `created_by_name` varchar(150) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `IDX_accounting_investor_transactions_branch_date` (`client_id`, `branch_id`, `transaction_date`),
  KEY `IDX_accounting_investor_transactions_investor_date` (`client_id`, `investor_id`, `transaction_date`),
  KEY `IDX_accounting_investor_transactions_agreement_date` (`client_id`, `agreement_id`, `transaction_date`),
  CONSTRAINT `FK_accounting_investor_transactions_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `FK_accounting_investor_transactions_investor` FOREIGN KEY (`investor_id`) REFERENCES `accounting_investors` (`id`),
  CONSTRAINT `FK_accounting_investor_transactions_agreement` FOREIGN KEY (`agreement_id`) REFERENCES `accounting_investor_agreements` (`id`),
  CONSTRAINT `FK_accounting_investor_transactions_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `FK_accounting_investor_transactions_batch` FOREIGN KEY (`distribution_batch_id`) REFERENCES `accounting_profit_distribution_batches` (`id`)
);
