import { APP_PERMISSIONS } from './permissions';

export type RoleTemplateScope = 'client' | 'branch';
export type RoleContextScope = 'branch' | 'central' | 'hybrid';
export type RoleApprovalAuthority = 'none' | 'branch' | 'central' | 'both';

export type DefaultRoleTemplate = {
  name: string;
  description: string;
  permissions: string[];
  templateScope: RoleTemplateScope;
  contextScope: RoleContextScope;
  approvalAuthority: RoleApprovalAuthority;
};

export const DEFAULT_ROLE_TEMPLATES: DefaultRoleTemplate[] = [
  {
    name: 'Client Admin',
    description: 'Tenant-wide administrator for branches, users, setup, catalog, reporting, and approvals.',
    permissions: ['all'],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'both',
  },
  {
    name: 'Group Admin',
    description: 'Company-level administrator for setup, access control, catalog standards, and multi-branch governance.',
    permissions: [
      APP_PERMISSIONS.ADMIN.DASHBOARD,
      APP_PERMISSIONS.ADMIN.ANALYTICS,
      APP_PERMISSIONS.ADMIN.SETUP_BRANCHES,
      APP_PERMISSIONS.ADMIN.SETUP_COUNTERS,
      APP_PERMISSIONS.ADMIN.SETUP_MASTER,
      APP_PERMISSIONS.ADMIN.SECURITY_USERS,
      APP_PERMISSIONS.ADMIN.SECURITY_ROLES,
      APP_PERMISSIONS.ADMIN.SECURITY_ACCESS,
      APP_PERMISSIONS.ADMIN.AUDIT_READ,
      APP_PERMISSIONS.ADMIN.SUBSCRIPTION,
      APP_PERMISSIONS.ADMIN.TAX_CONFIG,
      APP_PERMISSIONS.ADMIN.PAYMENT_METHODS,
      APP_PERMISSIONS.INVENTORY.LOCATIONS_MANAGE,
      APP_PERMISSIONS.INVENTORY.COUNT_SETTINGS,
      APP_PERMISSIONS.CATALOG.READ,
      APP_PERMISSIONS.CATALOG.WRITE,
      APP_PERMISSIONS.CATALOG.RECIPE_READ,
      APP_PERMISSIONS.CATALOG.RECIPE_WRITE,
      APP_PERMISSIONS.PROCUREMENT.VENDORS,
      APP_PERMISSIONS.PROCUREMENT.VENDORS_MANAGE,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.REPORTS,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'both',
  },
  {
    name: 'Owner',
    description: 'Business owner with company visibility and approval oversight without operational cash handling.',
    permissions: [
      APP_PERMISSIONS.ADMIN.DASHBOARD,
      APP_PERMISSIONS.ADMIN.ANALYTICS,
      APP_PERMISSIONS.ACCOUNTING.DASHBOARD,
      APP_PERMISSIONS.ACCOUNTING.REPORTS,
      APP_PERMISSIONS.HR.PAYROLL_READ,
      APP_PERMISSIONS.ACCOUNTING.INVESTORS_VIEW,
      APP_PERMISSIONS.ACCOUNTING.LOANS_VIEW,
      APP_PERMISSIONS.ACCOUNTING.PROFIT_DISTRIBUTION_VIEW,
      APP_PERMISSIONS.POS.REPORTS,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS,
      APP_PERMISSIONS.ADMIN.AUDIT_READ,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.APPROVE,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'both',
  },
  {
    name: 'Area Manager / GM',
    description: 'Multi-branch operator with performance, compliance, and approval responsibilities.',
    permissions: [
      APP_PERMISSIONS.ADMIN.DASHBOARD,
      APP_PERMISSIONS.ADMIN.ANALYTICS,
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.REPORTS,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.COUNT_REVIEW,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.HR.ATTENDANCE_READ,
      APP_PERMISSIONS.SEATING.VIEW,
      APP_PERMISSIONS.SERVICE.VIEW,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.REVIEW,
      APP_PERMISSIONS.APPROVAL.APPROVE,
    ],
    templateScope: 'client',
    contextScope: 'hybrid',
    approvalAuthority: 'both',
  },
  {
    name: 'Branch Admin',
    description: 'Primary branch-level administrator for local setup and operational recovery.',
    permissions: ['all'],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'both',
  },
  {
    name: 'Branch Manager',
    description: 'Branch-level operator in charge of sales, people, stock, and approvals.',
    permissions: [
      APP_PERMISSIONS.POS.ORDER_CREATE,
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.ORDER_CANCEL,
      APP_PERMISSIONS.POS.ORDER_RETURN,
      APP_PERMISSIONS.POS.SHIFT_MANAGE,
      APP_PERMISSIONS.POS.DAY_MANAGE,
      APP_PERMISSIONS.POS.TILL_MANAGE,
      APP_PERMISSIONS.POS.CASHIER_CONSOLE,
      APP_PERMISSIONS.POS.CREDIT_SETTLE,
      APP_PERMISSIONS.POS.ORDER_SEARCH,
      APP_PERMISSIONS.POS.CREDIT_ORDERS,
      APP_PERMISSIONS.POS.CREDIT_ORDERS_MANAGE,
      APP_PERMISSIONS.POS.RECEIPTS_PRINT,
      APP_PERMISSIONS.POS.KDS_READ,
      APP_PERMISSIONS.POS.REPORTS,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_SCHEDULE,
      APP_PERMISSIONS.INVENTORY.COUNT_PERFORM,
      APP_PERMISSIONS.INVENTORY.COUNT_REVIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_RECONCILE,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.INVENTORY.STOCK_ADJUST,
      APP_PERMISSIONS.INVENTORY.STOCK_RECEIVE,
      APP_PERMISSIONS.INVENTORY.STOCK_TRANSFER,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
      APP_PERMISSIONS.CRM.CUSTOMERS,
      APP_PERMISSIONS.CRM.CUSTOMERS_CREATE,
      APP_PERMISSIONS.CRM.CUSTOMERS_MANAGE,
      APP_PERMISSIONS.HR.STAFF_READ,
      APP_PERMISSIONS.HR.ATTENDANCE_READ,
      APP_PERMISSIONS.HR.ATTENDANCE_MARK,
      APP_PERMISSIONS.HR.PAYROLL_READ,
      APP_PERMISSIONS.SEATING.MANAGE,
      APP_PERMISSIONS.SERVICE.MANAGE,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.REVIEW,
      APP_PERMISSIONS.APPROVAL.APPROVE,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'branch',
  },
  {
    name: 'Supervisor',
    description: 'Shift leader for service recovery, operational overrides, and escalation review.',
    permissions: [
      APP_PERMISSIONS.POS.ORDER_CREATE,
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.ORDER_CANCEL,
      APP_PERMISSIONS.POS.ORDER_RETURN,
      APP_PERMISSIONS.POS.TILL_MANAGE,
      APP_PERMISSIONS.POS.CASHIER_CONSOLE,
      APP_PERMISSIONS.POS.CREDIT_SETTLE,
      APP_PERMISSIONS.POS.ORDER_SEARCH,
      APP_PERMISSIONS.POS.CREDIT_ORDERS,
      APP_PERMISSIONS.POS.CREDIT_ORDERS_MANAGE,
      APP_PERMISSIONS.POS.RECEIPTS_PRINT,
      APP_PERMISSIONS.POS.KDS_READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_PERFORM,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.CRM.CUSTOMERS,
      APP_PERMISSIONS.HR.ATTENDANCE_MARK,
      APP_PERMISSIONS.SEATING.MANAGE,
      APP_PERMISSIONS.SERVICE.MANAGE,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.REVIEW,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'branch',
  },
  {
    name: 'Cashier',
    description: 'Counter operator for billing, cashier console tasks, receipt handling, and customer lookup.',
    permissions: [
      APP_PERMISSIONS.POS.ORDER_CREATE,
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.CASHIER_CONSOLE,
      APP_PERMISSIONS.POS.CREDIT_SETTLE,
      APP_PERMISSIONS.POS.ORDER_SEARCH,
      APP_PERMISSIONS.POS.CREDIT_ORDERS,
      APP_PERMISSIONS.POS.RECEIPTS_PRINT,
      APP_PERMISSIONS.CRM.CUSTOMERS,
      APP_PERMISSIONS.CRM.CUSTOMERS_CREATE,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Order Taker',
    description: 'Mobile floor staff for table-side ordering only. No cash, reports, inventory, accounting, or approvals.',
    permissions: [
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.ORDER_CREATE,
      APP_PERMISSIONS.POS.ORDER_TAKER,
      APP_PERMISSIONS.CRM.CUSTOMERS,
      APP_PERMISSIONS.CRM.CUSTOMERS_CREATE,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Inventory Manager',
    description: 'Stock governance owner for catalog, recipes, branch stock controls, and wastage approvals.',
    permissions: [
      APP_PERMISSIONS.CATALOG.WRITE,
      APP_PERMISSIONS.CATALOG.CATEGORIES,
      APP_PERMISSIONS.CATALOG.RECIPE_WRITE,
      APP_PERMISSIONS.INVENTORY.SETUP,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_SCHEDULE,
      APP_PERMISSIONS.INVENTORY.COUNT_REVIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_RECONCILE,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.COUNT_SETTINGS,
      APP_PERMISSIONS.INVENTORY.LOCATIONS_MANAGE,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.INVENTORY.STOCK_ADJUST,
      APP_PERMISSIONS.INVENTORY.STOCK_RECEIVE,
      APP_PERMISSIONS.INVENTORY.STOCK_TRANSFER,
      APP_PERMISSIONS.INVENTORY.WASTAGE,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
      APP_PERMISSIONS.PROCUREMENT.VENDORS,
      APP_PERMISSIONS.PROCUREMENT.VENDORS_MANAGE,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS_MANAGE,
      APP_PERMISSIONS.PROCUREMENT.PAYMENTS,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.APPROVE,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'central',
  },
  {
    name: 'Store Manager',
    description: 'Store operator handling receiving, transfers, stock adjustments, and local stock execution.',
    permissions: [
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_PERFORM,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.STOCK_RECEIVE,
      APP_PERMISSIONS.INVENTORY.STOCK_TRANSFER,
      APP_PERMISSIONS.INVENTORY.STOCK_ADJUST,
      APP_PERMISSIONS.INVENTORY.WASTAGE,
      APP_PERMISSIONS.INVENTORY.LEDGER,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Asset Custodian',
    description: 'Branch custodian responsible for asset registration, issue-return, transfers, and condition tracking.',
    permissions: [
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Procurement Manager',
    description: 'Procurement head responsible for vendor relationships, purchase orders, and payment coordination.',
    permissions: [
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS,
      APP_PERMISSIONS.PROCUREMENT.VENDORS,
      APP_PERMISSIONS.PROCUREMENT.VENDORS_MANAGE,
      APP_PERMISSIONS.PROCUREMENT.PAYMENTS,
      APP_PERMISSIONS.PROCUREMENT.PURCHASE_ORDERS_MANAGE,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.CREATE,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'central',
  },
  {
    name: 'Accountant',
    description: 'Branch or company accountant focused on journals, vouchers, and reporting support.',
    permissions: [
      APP_PERMISSIONS.ACCOUNTING.DASHBOARD,
      APP_PERMISSIONS.ACCOUNTING.JOURNAL_READ,
      APP_PERMISSIONS.ACCOUNTING.JOURNAL_WRITE,
      APP_PERMISSIONS.ACCOUNTING.LEDGER,
      APP_PERMISSIONS.ACCOUNTING.COA,
      APP_PERMISSIONS.ACCOUNTING.COA_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.SETTINGS,
      APP_PERMISSIONS.ACCOUNTING.VOUCHER,
      APP_PERMISSIONS.ACCOUNTING.VOUCHER_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.PETTY_CASH,
      APP_PERMISSIONS.ACCOUNTING.PETTY_CASH_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.BANKS,
      APP_PERMISSIONS.ACCOUNTING.RECON,
      APP_PERMISSIONS.ACCOUNTING.INVESTORS_VIEW,
      APP_PERMISSIONS.ACCOUNTING.LOANS_VIEW,
      APP_PERMISSIONS.ACCOUNTING.PROFIT_DISTRIBUTION_VIEW,
      APP_PERMISSIONS.ACCOUNTING.REPORTS,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
      APP_PERMISSIONS.HR.PAYROLL_READ,
    ],
    templateScope: 'branch',
    contextScope: 'hybrid',
    approvalAuthority: 'none',
  },
  {
    name: 'Finance Manager',
    description: 'Finance controller for reconciliation, treasury, reporting, and approvals.',
    permissions: [
      APP_PERMISSIONS.ACCOUNTING.DASHBOARD,
      APP_PERMISSIONS.ACCOUNTING.JOURNAL_READ,
      APP_PERMISSIONS.ACCOUNTING.JOURNAL_WRITE,
      APP_PERMISSIONS.ACCOUNTING.JOURNAL_APPROVE,
      APP_PERMISSIONS.ACCOUNTING.LEDGER,
      APP_PERMISSIONS.ACCOUNTING.COA,
      APP_PERMISSIONS.ACCOUNTING.COA_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.SETTINGS,
      APP_PERMISSIONS.ACCOUNTING.VOUCHER,
      APP_PERMISSIONS.ACCOUNTING.VOUCHER_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.VOUCHER_APPROVE,
      APP_PERMISSIONS.ACCOUNTING.BANKS,
      APP_PERMISSIONS.ACCOUNTING.BANKS_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.RECON,
      APP_PERMISSIONS.ACCOUNTING.RECON_APPROVE,
      APP_PERMISSIONS.ACCOUNTING.PETTY_CASH,
      APP_PERMISSIONS.ACCOUNTING.PETTY_CASH_MANAGE,
      APP_PERMISSIONS.ACCOUNTING.INVESTORS,
      APP_PERMISSIONS.ACCOUNTING.LOANS,
      APP_PERMISSIONS.ACCOUNTING.PROFIT_DISTRIBUTION,
      APP_PERMISSIONS.ACCOUNTING.REPORTS,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.INVENTORY.MONTH_CLOSE,
      APP_PERMISSIONS.INVENTORY.ASSETS_VIEW,
      APP_PERMISSIONS.INVENTORY.ASSETS,
      APP_PERMISSIONS.HR.PAYROLL_READ,
      APP_PERMISSIONS.HR.PAYROLL_MANAGE,
      APP_PERMISSIONS.HR.PAYROLL_APPROVE,
      APP_PERMISSIONS.PROCUREMENT.PAYMENTS,
      APP_PERMISSIONS.PROCUREMENT.PAYMENTS_APPROVE,
      APP_PERMISSIONS.APPROVAL.VIEW,
      APP_PERMISSIONS.APPROVAL.APPROVE,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'both',
  },
  {
    name: 'HR Manager',
    description: 'Management of staff lifecycle, attendance, designations, and department structures.',
    permissions: [
      APP_PERMISSIONS.HR.STAFF_READ,
      APP_PERMISSIONS.HR.STAFF_WRITE,
      APP_PERMISSIONS.HR.ATTENDANCE_READ,
      APP_PERMISSIONS.HR.ATTENDANCE_MARK,
      APP_PERMISSIONS.HR.PAYROLL_READ,
      APP_PERMISSIONS.HR.PAYROLL_MANAGE,
      APP_PERMISSIONS.ADMIN.SETUP_MASTER,
      APP_PERMISSIONS.ADMIN.SECURITY_USERS,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'none',
  },
  {
    name: 'Kitchen Staff',
    description: 'Kitchen execution role for KDS flow, recipe adherence, and live order fulfillment.',
    permissions: [
      APP_PERMISSIONS.POS.ORDER_READ,
      APP_PERMISSIONS.POS.KDS_READ,
      APP_PERMISSIONS.POS.KDS_MANAGE,
      APP_PERMISSIONS.CATALOG.RECIPE_READ,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Seating Host',
    description: 'Front-of-house host responsible for seating, table layout, QR stations, and guest placement.',
    permissions: [
      APP_PERMISSIONS.SEATING.VIEW,
      APP_PERMISSIONS.SEATING.MANAGE,
      APP_PERMISSIONS.SERVICE.VIEW,
      APP_PERMISSIONS.SERVICE.MANAGE,
      APP_PERMISSIONS.CRM.CUSTOMERS,
      APP_PERMISSIONS.CRM.CUSTOMERS_CREATE,
      APP_PERMISSIONS.POS.ORDER_READ,
    ],
    templateScope: 'branch',
    contextScope: 'branch',
    approvalAuthority: 'none',
  },
  {
    name: 'Auditor',
    description: 'Read-only access to verify logs, inventory balances, approvals, and ledger entries.',
    permissions: [
      APP_PERMISSIONS.ADMIN.AUDIT_READ,
      APP_PERMISSIONS.ACCOUNTING.LEDGER,
      APP_PERMISSIONS.INVENTORY.READ,
      APP_PERMISSIONS.INVENTORY.COUNT_VIEW,
      APP_PERMISSIONS.INVENTORY.COUNT_REPORT,
      APP_PERMISSIONS.POS.REPORTS,
      APP_PERMISSIONS.APPROVAL.VIEW,
    ],
    templateScope: 'client',
    contextScope: 'central',
    approvalAuthority: 'none',
  },
];
