export const COUNTRY_OPTIONS: Array<{ value: string; label: string }> = [
    { value: '', label: 'Select country' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'Saudi Arabia', label: 'Saudi Arabia' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Bahrain', label: 'Bahrain' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'United States', label: 'United States' },
    { value: 'United Kingdom', label: 'United Kingdom' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Australia', label: 'Australia' },
];

export const CITY_OPTIONS: Array<{ value: string; label: string }> = [
    { value: '', label: 'Select city' },
    { value: 'Karachi', label: 'Karachi' },
    { value: 'Lahore', label: 'Lahore' },
    { value: 'Islamabad', label: 'Islamabad' },
    { value: 'Rawalpindi', label: 'Rawalpindi' },
    { value: 'Faisalabad', label: 'Faisalabad' },
    { value: 'Multan', label: 'Multan' },
    { value: 'Peshawar', label: 'Peshawar' },
    { value: 'Quetta', label: 'Quetta' },
    { value: 'Hyderabad', label: 'Hyderabad' },
    { value: 'Sialkot', label: 'Sialkot' },
    { value: 'Gujranwala', label: 'Gujranwala' },
    { value: 'Dubai', label: 'Dubai' },
    { value: 'Abu Dhabi', label: 'Abu Dhabi' },
    { value: 'Sharjah', label: 'Sharjah' },
    { value: 'Riyadh', label: 'Riyadh' },
    { value: 'Jeddah', label: 'Jeddah' },
    { value: 'Doha', label: 'Doha' },
    { value: 'Muscat', label: 'Muscat' },
    { value: 'Manama', label: 'Manama' },
    { value: 'Kuwait City', label: 'Kuwait City' },
    { value: 'London', label: 'London' },
    { value: 'New York', label: 'New York' },
    { value: 'Toronto', label: 'Toronto' },
    { value: 'Sydney', label: 'Sydney' },
];
